// Code generated by MockGen. DO NOT EDIT.
// Source: pg_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/AssylzhanZharzhanov/task-management-app/internal/domain/user"
	gomock "github.com/golang/mock/gomock"
)

// MockPostgresRepository is a mock of PostgresRepository interface.
type MockPostgresRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresRepositoryMockRecorder
}

// MockPostgresRepositoryMockRecorder is the mock recorder for MockPostgresRepository.
type MockPostgresRepositoryMockRecorder struct {
	mock *MockPostgresRepository
}

// NewMockPostgresRepository creates a new mock instance.
func NewMockPostgresRepository(ctrl *gomock.Controller) *MockPostgresRepository {
	mock := &MockPostgresRepository{ctrl: ctrl}
	mock.recorder = &MockPostgresRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresRepository) EXPECT() *MockPostgresRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostgresRepository) Create(user *domain.User) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPostgresRepositoryMockRecorder) Create(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostgresRepository)(nil).Create), user)
}

// Delete mocks base method.
func (m *MockPostgresRepository) Delete(userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostgresRepositoryMockRecorder) Delete(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostgresRepository)(nil).Delete), userID)
}

// GetByID mocks base method.
func (m *MockPostgresRepository) GetByID(userID domain.UserID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", userID)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostgresRepositoryMockRecorder) GetByID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostgresRepository)(nil).GetByID), userID)
}

// List mocks base method.
func (m *MockPostgresRepository) List() ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPostgresRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPostgresRepository)(nil).List))
}

// Update mocks base method.
func (m *MockPostgresRepository) Update(user *domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPostgresRepositoryMockRecorder) Update(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostgresRepository)(nil).Update), user)
}
