version: '3.4'

services:
  nginx:
    container_name: nginx
    image: nginx:1.16-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    command: "nginx -g 'daemon off;'"

  app:
    image: golang:1.17-alpine
    working_dir: /app
    command: go run cmd/api/main.go
    env_file:
      - configs/config.yml
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.4
    restart: always
    volumes:
      - data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"