version: '3.4'

services:
  nginx:
    container_name: nginx
    image: nginx:1.16-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    command: "nginx -g 'daemon off;'"

  app:
    container_name: app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: ./app
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    container_name: postgres
    image: postgres:13.4
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"