// Code generated by MockGen. DO NOT EDIT.
// Source: pg_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/AssylzhanZharzhanov/task-management-app/internal/domain/task"
	gomock "github.com/golang/mock/gomock"
)

// MockPostgresRepository is a mock of PostgresRepository interface.
type MockPostgresRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresRepositoryMockRecorder
}

// MockPostgresRepositoryMockRecorder is the mock recorder for MockPostgresRepository.
type MockPostgresRepositoryMockRecorder struct {
	mock *MockPostgresRepository
}

// NewMockPostgresRepository creates a new mock instance.
func NewMockPostgresRepository(ctrl *gomock.Controller) *MockPostgresRepository {
	mock := &MockPostgresRepository{ctrl: ctrl}
	mock.recorder = &MockPostgresRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresRepository) EXPECT() *MockPostgresRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostgresRepository) Create(task *domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPostgresRepositoryMockRecorder) Create(task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostgresRepository)(nil).Create), task)
}

// Delete mocks base method.
func (m *MockPostgresRepository) Delete(taskID domain.TaskID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostgresRepositoryMockRecorder) Delete(taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostgresRepository)(nil).Delete), taskID)
}

// GetByID mocks base method.
func (m *MockPostgresRepository) GetByID(taskID domain.TaskID) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", taskID)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostgresRepositoryMockRecorder) GetByID(taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostgresRepository)(nil).GetByID), taskID)
}

// List mocks base method.
func (m *MockPostgresRepository) List() ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPostgresRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPostgresRepository)(nil).List))
}

// Update mocks base method.
func (m *MockPostgresRepository) Update(task *domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPostgresRepositoryMockRecorder) Update(task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostgresRepository)(nil).Update), task)
}
